# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jaeun Choi
description: >- # this means to ignore newlines until "baseurl:"
  This is a developer website, a study blog.
baseurl: "" # the subpath of the site
url: "https://jaeun-choi98.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-monkey.png
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Study
    #- name: Work

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: chlwodns98@naver.com
      link: mailto:chlwodns98@naver.com
  follow:
    - name: GitHub
      link: http://github.com/Jaeun-Choi98
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
